
.TH tracker-store.cfg 5 "noviembre 2015" 1.6.1 "Tracker Manual"

.SH NAME
tracker-store.cfg

.SH SYNOPSIS
$HOME/.config/tracker/tracker-store.cfg

.SH DESCRIPTION
Tracker's configuration is built on top of GSettings, part of GLib. This means that there is a proper schema for configurations and they can be viewed (normally) using the \fBdconf-editor\fR tool.

Tracker also allows switching from the GSettings database, used by most (cross) desktop applications, to a key/value formatted files (like Microsoft's INI format). To do this, the environment variable \fBTRACKER_USE_CONFIG_FILES\fR must be defined before running the application using that configuration.

So where is this configuration? Well, normally they're stored in \fI$HOME/.config/tracker/\fR, however, default values are not stored to config files, only \fBdifferent\fR values are. This man page describes what keys and values can be used.

See EXAMPLES for a general overview.

.SH OPTIONS

.TP
\fBverbosity\fR='errors'
.nf

Log verbosity.
.fi


.TP
\fBgraphupdated-delay\fR=1000
.nf

Period in milliseconds between GraphUpdated signals being emitted when indexed data has changed inside the database.
.fi



.SH EXAMPLES
The top level group is "General". The default configuration (if saved to tracker-store.cfg), would look like:

.nf
    [General]
    verbosity='errors';
    graphupdated-delay=1000;
    
.fi

.SH SEE ALSO
.BR tracker-store\cfg
