
.TH tracker-extract.cfg 5 "marzo 2016" 1.7.3 "Tracker Manual"

.SH NAME
tracker-extract.cfg

.SH SYNOPSIS
$HOME/.config/tracker/tracker-extract.cfg

.SH DESCRIPTION
Tracker's configuration is built on top of GSettings, part of GLib. This means that there is a proper schema for configurations and they can be viewed (normally) using the \fBdconf-editor\fR tool.

Tracker also allows switching from the GSettings database, used by most (cross) desktop applications, to a key/value formatted files (like Microsoft's INI format). To do this, the environment variable \fBTRACKER_USE_CONFIG_FILES\fR must be defined before running the application using that configuration.

So where is this configuration? Well, normally they're stored in \fI$HOME/.config/tracker/\fR, however, default values are not stored to config files, only \fBdifferent\fR values are. This man page describes what keys and values can be used.

See EXAMPLES for a general overview.

.SH OPTIONS

.TP
\fBverbosity\fR='errors'
.nf

Log verbosity.
.fi


.TP
\fBsched-idle\fR='first-index'
.nf

The scheduler is the kernel component that decides which runnable application will be executed by the CPU next. Each application has an associated scheduling policy and priority.
.fi


.TP
\fBmax-bytes\fR=1048576
.nf

Maximum number of UTF-8 bytes to extract.
Values range from 0 to 10485760.

.fi


.TP
\fBmax-media-art-width\fR=0
.nf

Maximum width in pixels for any media art extracted. Anything bigger is resized. Set to -1 to disable saving media art from files. Setting to 0 sets no limit on the media art width.
Values range from -1 to 2048.

.fi


.TP
\fBwait-for-miner-fs\fR=false
.nf

When true, tracker-extract will wait for tracker-miner-fs to be done crawling before extracting meta-data. This option is useful on constrained environment where it is important to list files as fast as possible and can wait to get meta-data later.
.fi



.SH EXAMPLES
The top level group is "General". The default configuration (if saved to tracker-extract.cfg), would look like:

.nf
    [General]
    verbosity='errors';
    sched-idle='first-index';
    max-bytes=1048576;
    max-media-art-width=0;
    wait-for-miner-fs=false;
    
.fi

.SH SEE ALSO
.BR tracker-extract\cfg
