
.TH tracker-db.cfg 5 "marzo 2016" 1.7.5 "Tracker Manual"

.SH NAME
tracker-db.cfg

.SH SYNOPSIS
$HOME/.config/tracker/tracker-db.cfg

.SH DESCRIPTION
Tracker's configuration is built on top of GSettings, part of GLib. This means that there is a proper schema for configurations and they can be viewed (normally) using the \fBdconf-editor\fR tool.

Tracker also allows switching from the GSettings database, used by most (cross) desktop applications, to a key/value formatted files (like Microsoft's INI format). To do this, the environment variable \fBTRACKER_USE_CONFIG_FILES\fR must be defined before running the application using that configuration.

So where is this configuration? Well, normally they're stored in \fI$HOME/.config/tracker/\fR, however, default values are not stored to config files, only \fBdifferent\fR values are. This man page describes what keys and values can be used.

See EXAMPLES for a general overview.

.SH OPTIONS

.TP
\fBjournal-chunk-size\fR=50
.nf

Size of the journal at rotation in MB. Use -1 to disable rotating.
.fi


.TP
\fBjournal-rotate-destination\fR=''
.nf

Where to store a journal chunk when it hits the max size.
.fi



.SH EXAMPLES
The top level group is "General". The default configuration (if saved to tracker-db.cfg), would look like:

.nf
    [General]
    journal-chunk-size=50;
    journal-rotate-destination='';
    
.fi

.SH SEE ALSO
.BR tracker-db\cfg
