
.TH tracker-miner-fs.cfg 5 "marzo 2015" 1.3.6 "Tracker Manual"

.SH NAME
tracker-miner-fs.cfg

.SH SYNOPSIS
$HOME/.config/tracker/tracker-miner-fs.cfg

.SH DESCRIPTION
Tracker's configuration is built on top of GSettings, part of GLib. This means that there is a proper schema for configurations and they can be viewed (normally) using the \fBdconf-editor\fR tool.

Tracker also allows switching from the GSettings database, used by most (cross) desktop applications, to a key/value formatted files (like Microsoft's INI format). To do this, the environment variable \fBTRACKER_USE_CONFIG_FILES\fR must be defined before running the application using that configuration.

So where is this configuration? Well, normally they're stored in \fI$HOME/.config/tracker/\fR, however, default values are not stored to config files, only \fBdifferent\fR values are. This man page describes what keys and values can be used.

See EXAMPLES for a general overview.

.SH OPTIONS

.TP
\fBverbosity\fR='errors'
.nf

Log verbosity.
.fi


.TP
\fBinitial-sleep\fR=15
.nf

Initial sleep time, in seconds.
Values range from 0 to 1000.

.fi


.TP
\fBsched-idle\fR='first-index'
.nf

The scheduler is the kernel component that decides which runnable application will be executed by the CPU next. Each application has an associated scheduling policy and priority.
.fi


.TP
\fBthrottle\fR=0
.nf

Indexing speed, the higher the slower.
Values range from 0 to 20.

.fi


.TP
\fBlow-disk-space-limit\fR=-1
.nf

Disk space threshold in percent at which to pause indexing, or -1 to disable.
Values range from -1 to 100.

.fi


.TP
\fBcrawling-interval\fR=-1
.nf

Interval in days to check whether the filesystem is up to date in the database. 0 forces crawling anytime, -1 forces it only after unclean shutdowns, and -2 disables it entirely.
Values range from -2 to 365.

.fi


.TP
\fBremovable-days-threshold\fR=3
.nf

Threshold in days after which files from removables devices will be removed from database if not mounted. 0 means never, maximum is 365.
Values range from 0 to 365.

.fi


.TP
\fBenable-monitors\fR=true
.nf

Set to false to completely disable any file monitoring
.fi


.TP
\fBenable-writeback\fR=true
.nf

Set to false to completely disable any file writeback
.fi


.TP
\fBindex-removable-devices\fR=false
.nf

Set to true to enable indexing mounted directories for removable devices.
.fi


.TP
\fBindex-optical-discs\fR=false
.nf

Set to true to enable indexing CDs, DVDs, and generally optical media (if removable devices are not indexed, optical discs won't be either)
.fi


.TP
\fBindex-on-battery\fR=true
.nf

Set to true to index while running on battery
.fi


.TP
\fBindex-on-battery-first-time\fR=true
.nf

Set to true to index while running on battery for the first time only
.fi


.TP
\fBindex-recursive-directories\fR='&DESKTOP','&DOCUMENTS','&DOWNLOAD','&MUSIC','&PICTURES','&VIDEOS'
.nf

List of directories to index recursively, Special values include: &DESKTOP, &DOCUMENTS, &DOWNLOAD, &MUSIC, &PICTURES, &PUBLIC_SHARE, &TEMPLATES, &VIDEOS. See /etc/xdg/user-dirs.defaults and $HOME/.config/user-dirs.default
.fi


.TP
\fBindex-single-directories\fR='$HOME'
.nf

List of directories to index without inspecting subfolders, Special values include: &DESKTOP, &DOCUMENTS, &DOWNLOAD, &MUSIC, &PICTURES, &PUBLIC_SHARE, &TEMPLATES, &VIDEOS. See /etc/xdg/user-dirs.defaults and $HOME/.config/user-dirs.default
.fi


.TP
\fBignored-files\fR='*~','*.o','*.la','*.lo','*.loT','*.in','*.csproj','*.m4','*.rej','*.gmo','*.orig','*.pc','*.omf','*.aux','*.tmp','*.po','*.vmdk','*.vm*','*.nvram','*.part','*.rcore','*.lzo','autom4te','conftest','confstat','Makefile','SCCS','ltmain.sh','libtool','config.status','confdefs.h','configure'
.nf

List of file patterns to avoid
.fi


.TP
\fBignored-directories\fR='po','CVS','core-dumps','lost+found'
.nf

List of directories to avoid
.fi


.TP
\fBignored-directories-with-content\fR='.trackerignore'
.nf

Avoid any directory containing a file blacklisted here
.fi



.SH EXAMPLES
The top level group is "General". The default configuration (if saved to tracker-miner-fs.cfg), would look like:

.nf
    [General]
    verbosity='errors';
    initial-sleep=15;
    sched-idle='first-index';
    throttle=0;
    low-disk-space-limit=-1;
    crawling-interval=-1;
    removable-days-threshold=3;
    enable-monitors=true;
    enable-writeback=true;
    index-removable-devices=false;
    index-optical-discs=false;
    index-on-battery=true;
    index-on-battery-first-time=true;
    index-recursive-directories='&DESKTOP','&DOCUMENTS','&DOWNLOAD','&MUSIC','&PICTURES','&VIDEOS';
    index-single-directories='$HOME';
    ignored-files='*~','*.o','*.la','*.lo','*.loT','*.in','*.csproj','*.m4','*.rej','*.gmo','*.orig','*.pc','*.omf','*.aux','*.tmp','*.po','*.vmdk','*.vm*','*.nvram','*.part','*.rcore','*.lzo','autom4te','conftest','confstat','Makefile','SCCS','ltmain.sh','libtool','config.status','confdefs.h','configure';
    ignored-directories='po','CVS','core-dumps','lost+found';
    ignored-directories-with-content='.trackerignore';
    
.fi

.SH SEE ALSO
.BR tracker-miner-fs\cfg
