
.TH tracker-fts.cfg 5 "July 2015" 1.4.1 "Tracker Manual"

.SH NAME
tracker-fts.cfg

.SH SYNOPSIS
$HOME/.config/tracker/tracker-fts.cfg

.SH DESCRIPTION
Tracker's configuration is built on top of GSettings, part of GLib. This means that there is a proper schema for configurations and they can be viewed (normally) using the \fBdconf-editor\fR tool.

Tracker also allows switching from the GSettings database, used by most (cross) desktop applications, to a key/value formatted files (like Microsoft's INI format). To do this, the environment variable \fBTRACKER_USE_CONFIG_FILES\fR must be defined before running the application using that configuration.

So where is this configuration? Well, normally they're stored in \fI$HOME/.config/tracker/\fR, however, default values are not stored to config files, only \fBdifferent\fR values are. This man page describes what keys and values can be used.

See EXAMPLES for a general overview.

.SH OPTIONS

.TP
\fBmax-word-length\fR=30
.nf

Words with more characters than this length will be ignored by the indexer.
Values range from 0 to 200.

.fi


.TP
\fBmax-words-to-index\fR=10000
.nf

Indexer will read only this maximum number of words from a single document.
.fi


.TP
\fBenable-stemmer\fR=false
.nf

Simplify the words to their root to provide more results. E.g. 'shelves' and 'shelf' to 'shel'
.fi


.TP
\fBenable-unaccent\fR=true
.nf

Translate accented characters to the equivalent unaccented. E.g. 'Idéa' to 'Idea' for improved matching.
.fi


.TP
\fBignore-numbers\fR=true
.nf

If enabled, numbers will not be indexed.
.fi


.TP
\fBignore-stop-words\fR=true
.nf

If enabled, the words listed in the stop-words list are ignored. E.g. common words like 'the', 'yes', 'no', etc.
.fi



.SH EXAMPLES
The top level group is "General". The default configuration (if saved to tracker-fts.cfg), would look like:

.nf
    [General]
    max-word-length=30;
    max-words-to-index=10000;
    enable-stemmer=false;
    enable-unaccent=true;
    ignore-numbers=true;
    ignore-stop-words=true;
    
.fi

.SH SEE ALSO
.BR tracker-fts\cfg
