/* tracker-stats.c generated by valac 0.28.0, the Vala compiler
 * generated from tracker-stats.vala, do not modify */

/**/
/* Copyright 2010, Martyn Russell <martyn@lanedo.com>*/
/**/
/* This program is free software; you can redistribute it and/or*/
/* modify it under the terms of the GNU General Public License*/
/* as published by the Free Software Foundation; either version 2*/
/* of the License, or (at your option) any later version.*/
/**/
/* This program is distributed in the hope that it will be useful,*/
/* but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/* GNU General Public License for more details.*/
/**/
/* You should have received a copy of the GNU General Public License*/
/* along with this program; if not, write to the Free Software*/
/* Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA*/
/* 02110-1301, USA.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include "config.h"
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>


#define TYPE_STATISTICS (statistics_get_type ())
#define STATISTICS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_STATISTICS, Statistics))
#define IS_STATISTICS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_STATISTICS))
#define STATISTICS_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), TYPE_STATISTICS, StatisticsIface))

typedef struct _Statistics Statistics;
typedef struct _StatisticsIface StatisticsIface;

#define TYPE_STATISTICS_PROXY (statistics_proxy_get_type ())
typedef GDBusProxy StatisticsProxy;
typedef GDBusProxyClass StatisticsProxyClass;

#define TRACKER_TYPE_STATS (tracker_stats_get_type ())
#define TRACKER_STATS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TRACKER_TYPE_STATS, TrackerStats))
#define TRACKER_STATS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TRACKER_TYPE_STATS, TrackerStatsClass))
#define TRACKER_IS_STATS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TRACKER_TYPE_STATS))
#define TRACKER_IS_STATS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TRACKER_TYPE_STATS))
#define TRACKER_STATS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TRACKER_TYPE_STATS, TrackerStatsClass))

typedef struct _TrackerStats TrackerStats;
typedef struct _TrackerStatsClass TrackerStatsClass;
typedef struct _TrackerStatsPrivate TrackerStatsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _StatisticsIface {
	GTypeInterface parent_iface;
	gchar** (*Get) (Statistics* self, int* result_length1, int* result_length2, GError** error);
};

struct _TrackerStats {
	GtkDialog parent_instance;
	TrackerStatsPrivate * priv;
};

struct _TrackerStatsClass {
	GtkDialogClass parent_class;
};

struct _TrackerStatsPrivate {
	Statistics* tracker;
};


static gpointer tracker_stats_parent_class = NULL;

#define b PACKAGE_NAME
GType statistics_proxy_get_type (void) G_GNUC_CONST;
guint statistics_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType statistics_get_type (void) G_GNUC_CONST;
gchar** statistics_Get (Statistics* self, int* result_length1, int* result_length2, GError** error);
static void statistics_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters);
static gchar** statistics_proxy_Get (Statistics* self, int* result_length1, int* result_length2, GError** error);
static void statistics_proxy_statistics_interface_init (StatisticsIface* iface);
static void _dbus_statistics_Get (Statistics* self, GVariant* _parameters_, GDBusMethodInvocation* invocation);
static void statistics_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data);
static GVariant* statistics_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data);
static gboolean statistics_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data);
static void _statistics_unregister_object (gpointer user_data);
GType tracker_stats_get_type (void) G_GNUC_CONST;
#define TRACKER_STATS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TRACKER_TYPE_STATS, TrackerStatsPrivate))
enum  {
	TRACKER_STATS_DUMMY_PROPERTY
};
TrackerStats* tracker_stats_new (void);
TrackerStats* tracker_stats_construct (GType object_type);
static void tracker_stats_setup_dbus (TrackerStats* self);
static void tracker_stats_setup_ui (TrackerStats* self);
static void tracker_stats_on_response (TrackerStats* self, GtkDialog* source, gint response_id);
static void _tracker_stats_on_response_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self);
static void tracker_stats_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

static const GDBusArgInfo _statistics_dbus_arg_info_Get_result = {-1, "result", "aas"};
static const GDBusArgInfo * const _statistics_dbus_arg_info_Get_in[] = {NULL};
static const GDBusArgInfo * const _statistics_dbus_arg_info_Get_out[] = {&_statistics_dbus_arg_info_Get_result, NULL};
static const GDBusMethodInfo _statistics_dbus_method_info_Get = {-1, "Get", (GDBusArgInfo **) (&_statistics_dbus_arg_info_Get_in), (GDBusArgInfo **) (&_statistics_dbus_arg_info_Get_out)};
static const GDBusMethodInfo * const _statistics_dbus_method_info[] = {&_statistics_dbus_method_info_Get, NULL};
static const GDBusSignalInfo * const _statistics_dbus_signal_info[] = {NULL};
static const GDBusPropertyInfo * const _statistics_dbus_property_info[] = {NULL};
static const GDBusInterfaceInfo _statistics_dbus_interface_info = {-1, "org.freedesktop.Tracker1.Statistics", (GDBusMethodInfo **) (&_statistics_dbus_method_info), (GDBusSignalInfo **) (&_statistics_dbus_signal_info), (GDBusPropertyInfo **) (&_statistics_dbus_property_info)};
static const GDBusInterfaceVTable _statistics_dbus_interface_vtable = {statistics_dbus_interface_method_call, statistics_dbus_interface_get_property, statistics_dbus_interface_set_property};

gchar** statistics_Get (Statistics* self, int* result_length1, int* result_length2, GError** error) {
#line 27 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 27 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	return STATISTICS_GET_INTERFACE (self)->Get (self, result_length1, result_length2, error);
#line 124 "tracker-stats.c"
}


static void statistics_base_init (StatisticsIface * iface) {
#line 26 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	static gboolean initialized = FALSE;
#line 26 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	if (!initialized) {
#line 26 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		initialized = TRUE;
#line 135 "tracker-stats.c"
	}
}


GType statistics_get_type (void) {
	static volatile gsize statistics_type_id__volatile = 0;
	if (g_once_init_enter (&statistics_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (StatisticsIface), (GBaseInitFunc) statistics_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType statistics_type_id;
		statistics_type_id = g_type_register_static (G_TYPE_INTERFACE, "Statistics", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (statistics_type_id, G_TYPE_DBUS_PROXY);
		g_type_set_qdata (statistics_type_id, g_quark_from_static_string ("vala-dbus-proxy-type"), (void*) statistics_proxy_get_type);
		g_type_set_qdata (statistics_type_id, g_quark_from_static_string ("vala-dbus-interface-name"), "org.freedesktop.Tracker1.Statistics");
		g_type_set_qdata (statistics_type_id, g_quark_from_static_string ("vala-dbus-interface-info"), (void*) (&_statistics_dbus_interface_info));
		g_type_set_qdata (statistics_type_id, g_quark_from_static_string ("vala-dbus-register-object"), (void*) statistics_register_object);
		g_once_init_leave (&statistics_type_id__volatile, statistics_type_id);
	}
	return statistics_type_id__volatile;
}


G_DEFINE_TYPE_EXTENDED (StatisticsProxy, statistics_proxy, G_TYPE_DBUS_PROXY, 0, G_IMPLEMENT_INTERFACE (TYPE_STATISTICS, statistics_proxy_statistics_interface_init) )
static void statistics_proxy_class_init (StatisticsProxyClass* klass) {
	G_DBUS_PROXY_CLASS (klass)->g_signal = statistics_proxy_g_signal;
}


static void statistics_proxy_g_signal (GDBusProxy* proxy, const gchar* sender_name, const gchar* signal_name, GVariant* parameters) {
}


static void statistics_proxy_init (StatisticsProxy* self) {
}


static gchar** statistics_proxy_Get (Statistics* self, int* result_length1, int* result_length2, GError** error) {
	GDBusMessage *_message;
	GVariant *_arguments;
	GVariantBuilder _arguments_builder;
	GDBusMessage *_reply_message;
	GVariant *_reply;
	GVariantIter _reply_iter;
	gchar** _result;
	int _result_length1;
	int _result_length2;
	GVariant* _tmp0_;
	gchar** _tmp1_;
	int _tmp1__length;
	int _tmp1__size;
	int _tmp1__length1;
	GVariantIter _tmp2_;
	GVariant* _tmp3_;
	G_DBUS_ERROR;
	_message = g_dbus_message_new_method_call (g_dbus_proxy_get_name ((GDBusProxy *) self), g_dbus_proxy_get_object_path ((GDBusProxy *) self), "org.freedesktop.Tracker1.Statistics", "Get");
	g_variant_builder_init (&_arguments_builder, G_VARIANT_TYPE_TUPLE);
	_arguments = g_variant_builder_end (&_arguments_builder);
	g_dbus_message_set_body (_message, _arguments);
	_reply_message = g_dbus_connection_send_message_with_reply_sync (g_dbus_proxy_get_connection ((GDBusProxy *) self), _message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, g_dbus_proxy_get_default_timeout ((GDBusProxy *) self), NULL, NULL, error);
	g_object_unref (_message);
	if (!_reply_message) {
		return NULL;
	}
	if (g_dbus_message_to_gerror (_reply_message, error)) {
		g_object_unref (_reply_message);
		return NULL;
	}
	_reply = g_dbus_message_get_body (_reply_message);
	g_variant_iter_init (&_reply_iter, _reply);
	_result_length1 = 0;
	_result_length2 = 0;
	_tmp0_ = g_variant_iter_next_value (&_reply_iter);
	_tmp1_ = g_new (gchar*, 5);
	_tmp1__length = 0;
	_tmp1__size = 4;
	_tmp1__length1 = 0;
	g_variant_iter_init (&_tmp2_, _tmp0_);
	for (; (_tmp3_ = g_variant_iter_next_value (&_tmp2_)) != NULL; _tmp1__length1++) {
		int _tmp1__length2;
		GVariantIter _tmp4_;
		GVariant* _tmp5_;
		_tmp1__length2 = 0;
		g_variant_iter_init (&_tmp4_, _tmp3_);
		for (; (_tmp5_ = g_variant_iter_next_value (&_tmp4_)) != NULL; _tmp1__length2++) {
			if (_tmp1__size == _tmp1__length) {
				_tmp1__size = 2 * _tmp1__size;
				_tmp1_ = g_renew (gchar*, _tmp1_, _tmp1__size + 1);
			}
			_tmp1_[_tmp1__length++] = g_variant_dup_string (_tmp5_, NULL);
			g_variant_unref (_tmp5_);
		}
		_result_length2 = _tmp1__length2;
		g_variant_unref (_tmp3_);
	}
	_result_length1 = _tmp1__length1;
	_tmp1_[_tmp1__length] = NULL;
	_result = _tmp1_;
	g_variant_unref (_tmp0_);
	*result_length1 = _result_length1;
	*result_length2 = _result_length2;
	g_object_unref (_reply_message);
	return _result;
}


static void statistics_proxy_statistics_interface_init (StatisticsIface* iface) {
	iface->Get = statistics_proxy_Get;
}


static void _dbus_statistics_Get (Statistics* self, GVariant* _parameters_, GDBusMethodInvocation* invocation) {
	GError* error = NULL;
	GVariantIter _arguments_iter;
	GDBusMessage* _reply_message;
	GVariant* _reply;
	GVariantBuilder _reply_builder;
	gchar** result;
	int result_length1 = 0;
	int result_length2 = 0;
	gchar** _tmp6_;
	GVariantBuilder _tmp7_;
	int _tmp8_;
	g_variant_iter_init (&_arguments_iter, _parameters_);
	result = statistics_Get (self, &result_length1, &result_length2, &error);
	if (error) {
		g_dbus_method_invocation_return_gerror (invocation, error);
		return;
	}
	_reply_message = g_dbus_message_new_method_reply (g_dbus_method_invocation_get_message (invocation));
	g_variant_builder_init (&_reply_builder, G_VARIANT_TYPE_TUPLE);
	_tmp6_ = result;
	g_variant_builder_init (&_tmp7_, G_VARIANT_TYPE ("aas"));
	for (_tmp8_ = 0; _tmp8_ < result_length1; _tmp8_++) {
		GVariantBuilder _tmp9_;
		int _tmp10_;
		g_variant_builder_init (&_tmp9_, G_VARIANT_TYPE ("aas"));
		for (_tmp10_ = 0; _tmp10_ < result_length2; _tmp10_++) {
			g_variant_builder_add_value (&_tmp9_, g_variant_new_string (*_tmp6_));
			_tmp6_++;
		}
		g_variant_builder_add_value (&_tmp7_, g_variant_builder_end (&_tmp9_));
	}
	g_variant_builder_add_value (&_reply_builder, g_variant_builder_end (&_tmp7_));
	result = (_vala_array_free (result, result_length1 * result_length2, (GDestroyNotify) g_free), NULL);
	_reply = g_variant_builder_end (&_reply_builder);
	g_dbus_message_set_body (_reply_message, _reply);
	g_dbus_connection_send_message (g_dbus_method_invocation_get_connection (invocation), _reply_message, G_DBUS_SEND_MESSAGE_FLAGS_NONE, NULL, NULL);
	g_object_unref (invocation);
	g_object_unref (_reply_message);
}


static void statistics_dbus_interface_method_call (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* method_name, GVariant* parameters, GDBusMethodInvocation* invocation, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	if (strcmp (method_name, "Get") == 0) {
		_dbus_statistics_Get (object, parameters, invocation);
	} else {
		g_object_unref (invocation);
	}
}


static GVariant* statistics_dbus_interface_get_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return NULL;
}


static gboolean statistics_dbus_interface_set_property (GDBusConnection* connection, const gchar* sender, const gchar* object_path, const gchar* interface_name, const gchar* property_name, GVariant* value, GError** error, gpointer user_data) {
	gpointer* data;
	gpointer object;
	data = user_data;
	object = data[0];
	return FALSE;
}


guint statistics_register_object (gpointer object, GDBusConnection* connection, const gchar* path, GError** error) {
	guint result;
	gpointer *data;
	data = g_new (gpointer, 3);
	data[0] = g_object_ref (object);
	data[1] = g_object_ref (connection);
	data[2] = g_strdup (path);
	result = g_dbus_connection_register_object (connection, path, (GDBusInterfaceInfo *) (&_statistics_dbus_interface_info), &_statistics_dbus_interface_vtable, data, _statistics_unregister_object, error);
	if (!result) {
		return 0;
	}
	return result;
}


static void _statistics_unregister_object (gpointer user_data) {
	gpointer* data;
	data = user_data;
	g_object_unref (data[0]);
	g_object_unref (data[1]);
	g_free (data[2]);
	g_free (data);
}


TrackerStats* tracker_stats_construct (GType object_type) {
	TrackerStats * self = NULL;
#line 33 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	self = (TrackerStats*) g_object_new (object_type, NULL);
#line 34 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_window_set_title ((GtkWindow*) self, "Statistics");
#line 35 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_container_set_border_width ((GtkContainer*) self, (guint) 12);
#line 36 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_window_set_resizable ((GtkWindow*) self, FALSE);
#line 38 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	tracker_stats_setup_dbus (self);
#line 39 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	tracker_stats_setup_ui (self);
#line 33 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	return self;
#line 359 "tracker-stats.c"
}


TrackerStats* tracker_stats_new (void) {
#line 33 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	return tracker_stats_construct (TRACKER_TYPE_STATS);
#line 366 "tracker-stats.c"
}


static void tracker_stats_setup_dbus (TrackerStats* self) {
	GError * _inner_error_ = NULL;
#line 42 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_return_if_fail (self != NULL);
#line 43 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_debug ("tracker-stats.vala:43: Setting up statistics D-Bus connection");
#line 376 "tracker-stats.c"
	{
		Statistics* _tmp0_ = NULL;
		Statistics* _tmp1_ = NULL;
		Statistics* _tmp2_ = NULL;
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp1_ = g_initable_new (TYPE_STATISTICS_PROXY, NULL, &_inner_error_, "g-flags", G_DBUS_PROXY_FLAGS_DO_NOT_LOAD_PROPERTIES | G_DBUS_PROXY_FLAGS_DO_NOT_CONNECT_SIGNALS, "g-name", "org.freedesktop.Tracker1", "g-bus-type", G_BUS_TYPE_SESSION, "g-object-path", "/org/freedesktop/Tracker1/Statistics", "g-interface-name", "org.freedesktop.Tracker1.Statistics", "g-interface-info", g_type_get_qdata (TYPE_STATISTICS, g_quark_from_static_string ("vala-dbus-interface-info")), NULL);
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp0_ = (Statistics*) _tmp1_;
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			if (_inner_error_->domain == G_IO_ERROR) {
#line 389 "tracker-stats.c"
				goto __catch11_g_io_error;
			}
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			g_clear_error (&_inner_error_);
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			return;
#line 398 "tracker-stats.c"
		}
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp2_ = _tmp0_;
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp0_ = NULL;
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_object_unref0 (self->priv->tracker);
#line 46 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		self->priv->tracker = _tmp2_;
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_object_unref0 (_tmp0_);
#line 410 "tracker-stats.c"
	}
	goto __finally11;
	__catch11_g_io_error:
	{
		GError* e = NULL;
		GtkMessageDialog* msg = NULL;
		GError* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		GtkMessageDialog* _tmp5_ = NULL;
		GtkMessageDialog* _tmp6_ = NULL;
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		e = _inner_error_;
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_inner_error_ = NULL;
#line 51 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp3_ = e;
#line 51 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp4_ = _tmp3_->message;
#line 51 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp5_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_ERROR, GTK_BUTTONS_CANCEL, "Error connecting to D-Bus session bus, %s", _tmp4_);
#line 51 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		g_object_ref_sink (_tmp5_);
#line 51 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		msg = _tmp5_;
#line 57 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp6_ = msg;
#line 57 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		gtk_dialog_run ((GtkDialog*) _tmp6_);
#line 58 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		gtk_main_quit ();
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_object_unref0 (msg);
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_error_free0 (e);
#line 445 "tracker-stats.c"
	}
	__finally11:
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		g_clear_error (&_inner_error_);
#line 45 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		return;
#line 456 "tracker-stats.c"
	}
}


static gpointer _g_object_ref0 (gpointer self) {
#line 66 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	return self ? g_object_ref (self) : NULL;
#line 464 "tracker-stats.c"
}


static void _tracker_stats_on_response_gtk_dialog_response (GtkDialog* _sender, gint response_id, gpointer self) {
#line 179 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	tracker_stats_on_response ((TrackerStats*) self, _sender, response_id);
#line 471 "tracker-stats.c"
}


static void tracker_stats_setup_ui (TrackerStats* self) {
	GtkBox* vbox = NULL;
	GtkBox* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	GtkBox* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	GtkLabel* label = NULL;
	const gchar* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	GtkLabel* _tmp6_ = NULL;
	GtkLabel* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkBox* _tmp9_ = NULL;
	GtkLabel* _tmp10_ = NULL;
	GtkSizeGroup* sizegroup = NULL;
	GtkSizeGroup* _tmp11_ = NULL;
	GtkBox* _tmp114_ = NULL;
	GError * _inner_error_ = NULL;
#line 62 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_return_if_fail (self != NULL);
#line 63 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_debug ("tracker-stats.vala:63: Setting up statistics UI");
#line 66 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp0_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
#line 66 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp1_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (_tmp0_, gtk_box_get_type ()) ? ((GtkBox*) _tmp0_) : NULL);
#line 66 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	vbox = _tmp1_;
#line 67 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp2_ = vbox;
#line 67 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_box_set_spacing (_tmp2_, 18);
#line 68 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp3_ = vbox;
#line 68 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_container_set_border_width ((GtkContainer*) _tmp3_, (guint) 0);
#line 71 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp4_ = _ ("The statistics represented here do not reflect their availability, rat" \
"her the total data stored:");
#line 71 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp5_ = (GtkLabel*) gtk_label_new (_tmp4_);
#line 71 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_object_ref_sink (_tmp5_);
#line 71 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	label = _tmp5_;
#line 72 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp6_ = label;
#line 72 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_label_set_line_wrap (_tmp6_, TRUE);
#line 73 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp7_ = label;
#line 73 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_label_set_max_width_chars (_tmp7_, 50);
#line 74 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp8_ = label;
#line 74 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_misc_set_alignment ((GtkMisc*) _tmp8_, 0.0f, 0.5f);
#line 80 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp9_ = vbox;
#line 80 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp10_ = label;
#line 80 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_box_pack_start (_tmp9_, (GtkWidget*) _tmp10_, TRUE, TRUE, (guint) 0);
#line 83 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp11_ = gtk_size_group_new (GTK_SIZE_GROUP_HORIZONTAL);
#line 83 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	sizegroup = _tmp11_;
#line 541 "tracker-stats.c"
	{
		gchar** _result_ = NULL;
		Statistics* _tmp12_ = NULL;
		gint _tmp13_ = 0;
		gint _tmp14_ = 0;
		gchar** _tmp15_ = NULL;
		gint _result__length1 = 0;
		gint _result__length2 = 0;
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp12_ = self->priv->tracker;
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp15_ = statistics_Get (_tmp12_, &_tmp13_, &_tmp14_, &_inner_error_);
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_result_ = _tmp15_;
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_result__length1 = _tmp13_;
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_result__length2 = _tmp14_;
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			if (_inner_error_->domain == G_DBUS_ERROR) {
#line 564 "tracker-stats.c"
				goto __catch12_g_dbus_error;
			}
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			_g_object_unref0 (sizegroup);
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			_g_object_unref0 (label);
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			_g_object_unref0 (vbox);
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			g_clear_error (&_inner_error_);
#line 86 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			return;
#line 579 "tracker-stats.c"
		}
		{
			gint i = 0;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			i = 0;
#line 585 "tracker-stats.c"
			{
				gboolean _tmp16_ = FALSE;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
				_tmp16_ = TRUE;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
				while (TRUE) {
#line 592 "tracker-stats.c"
					gint _tmp18_ = 0;
					gchar** _tmp19_ = NULL;
					gint _tmp19__length1 = 0;
					gint _tmp19__length2 = 0;
					gint _tmp20_ = 0;
					gchar* key = NULL;
					gchar** _tmp21_ = NULL;
					gint _tmp21__length1 = 0;
					gint _tmp21__length2 = 0;
					gint _tmp22_ = 0;
					const gchar* _tmp23_ = NULL;
					gchar* _tmp24_ = NULL;
					gchar* val = NULL;
					gchar** _tmp25_ = NULL;
					gint _tmp25__length1 = 0;
					gint _tmp25__length2 = 0;
					gint _tmp26_ = 0;
					const gchar* _tmp27_ = NULL;
					gchar* _tmp28_ = NULL;
					gchar* key_used = NULL;
					const gchar* _tmp29_ = NULL;
					const gchar* _tmp30_ = NULL;
					const gchar* _tmp31_ = NULL;
					const gchar* _tmp32_ = NULL;
					GQuark _tmp34_ = 0U;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label0 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label1 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label2 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label3 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label4 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label5 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label6 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label7 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label8 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label9 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label10 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label11 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label12 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label13 = 0;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					static GQuark _tmp33_label14 = 0;
#line 648 "tracker-stats.c"
					GtkBox* box = NULL;
					GtkBox* _tmp95_ = NULL;
					GtkLabel* label_key = NULL;
					const gchar* _tmp96_ = NULL;
					GtkLabel* _tmp97_ = NULL;
					GtkLabel* label_val = NULL;
					const gchar* _tmp98_ = NULL;
					GtkLabel* _tmp99_ = NULL;
					GtkLabel* _tmp100_ = NULL;
					GtkLabel* _tmp101_ = NULL;
					GtkBox* _tmp102_ = NULL;
					GtkLabel* _tmp103_ = NULL;
					GtkBox* _tmp104_ = NULL;
					GtkLabel* _tmp105_ = NULL;
					GtkSizeGroup* _tmp106_ = NULL;
					GtkLabel* _tmp107_ = NULL;
					GtkBox* _tmp108_ = NULL;
					GtkBox* _tmp109_ = NULL;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					if (!_tmp16_) {
#line 669 "tracker-stats.c"
						gint _tmp17_ = 0;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						_tmp17_ = i;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						i = _tmp17_ + 1;
#line 675 "tracker-stats.c"
					}
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp16_ = FALSE;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp18_ = i;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp19_ = _result_;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp19__length1 = _result__length1;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp19__length2 = _result__length2;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp20_ = _tmp19__length1;
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					if (!(_tmp18_ < _tmp20_)) {
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						break;
#line 693 "tracker-stats.c"
					}
#line 89 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp21_ = _result_;
#line 89 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp21__length1 = _result__length1;
#line 89 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp21__length2 = _result__length2;
#line 89 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp22_ = i;
#line 89 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp23_ = _tmp21_[(_tmp22_ * _tmp21__length2) + 0];
#line 89 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp24_ = g_strdup (_tmp23_);
#line 89 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					key = _tmp24_;
#line 90 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp25_ = _result_;
#line 90 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp25__length1 = _result__length1;
#line 90 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp25__length2 = _result__length2;
#line 90 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp26_ = i;
#line 90 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp27_ = _tmp25_[(_tmp26_ * _tmp25__length2) + 1];
#line 90 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp28_ = g_strdup (_tmp27_);
#line 90 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					val = _tmp28_;
#line 93 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp29_ = key;
#line 93 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp30_ = val;
#line 93 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					g_debug ("tracker-stats.vala:93: --> %s = %s", _tmp29_, _tmp30_);
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp31_ = key;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp32_ = _tmp31_;
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp34_ = (NULL == _tmp32_) ? 0 : g_quark_from_string (_tmp32_);
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					if (_tmp34_ == ((0 != _tmp33_label0) ? _tmp33_label0 : (_tmp33_label0 = g_quark_from_static_string ("nao:Tag")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 739 "tracker-stats.c"
							default:
							{
								const gchar* _tmp35_ = NULL;
								gint _tmp36_ = 0;
								const gchar* _tmp37_ = NULL;
								gchar* _tmp38_ = NULL;
#line 97 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp35_ = val;
#line 97 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp36_ = atoi (_tmp35_);
#line 97 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp37_ = ngettext ("Tag", "Tags", (gulong) _tmp36_);
#line 97 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp38_ = g_strdup (_tmp37_);
#line 97 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 97 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp38_;
#line 98 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 760 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label1) ? _tmp33_label1 : (_tmp33_label1 = g_quark_from_static_string ("nco:Contact")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 766 "tracker-stats.c"
							default:
							{
								const gchar* _tmp39_ = NULL;
								gint _tmp40_ = 0;
								const gchar* _tmp41_ = NULL;
								gchar* _tmp42_ = NULL;
#line 100 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp39_ = val;
#line 100 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp40_ = atoi (_tmp39_);
#line 100 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp41_ = ngettext ("Contact", "Contacts", (gulong) _tmp40_);
#line 100 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp42_ = g_strdup (_tmp41_);
#line 100 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 100 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp42_;
#line 101 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 787 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label2) ? _tmp33_label2 : (_tmp33_label2 = g_quark_from_static_string ("nfo:Audio")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 793 "tracker-stats.c"
							default:
							{
								const gchar* _tmp43_ = NULL;
								gint _tmp44_ = 0;
								const gchar* _tmp45_ = NULL;
								gchar* _tmp46_ = NULL;
#line 103 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp43_ = val;
#line 103 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp44_ = atoi (_tmp43_);
#line 103 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp45_ = ngettext ("Audio", "Audios", (gulong) _tmp44_);
#line 103 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp46_ = g_strdup (_tmp45_);
#line 103 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 103 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp46_;
#line 104 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 814 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label3) ? _tmp33_label3 : (_tmp33_label3 = g_quark_from_static_string ("nfo:Document")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 820 "tracker-stats.c"
							default:
							{
								const gchar* _tmp47_ = NULL;
								gint _tmp48_ = 0;
								const gchar* _tmp49_ = NULL;
								gchar* _tmp50_ = NULL;
#line 106 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp47_ = val;
#line 106 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp48_ = atoi (_tmp47_);
#line 106 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp49_ = ngettext ("Document", "Documents", (gulong) _tmp48_);
#line 106 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp50_ = g_strdup (_tmp49_);
#line 106 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 106 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp50_;
#line 107 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 841 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label4) ? _tmp33_label4 : (_tmp33_label4 = g_quark_from_static_string ("nfo:FileDataObject")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 847 "tracker-stats.c"
							default:
							{
								const gchar* _tmp51_ = NULL;
								gint _tmp52_ = 0;
								const gchar* _tmp53_ = NULL;
								gchar* _tmp54_ = NULL;
#line 109 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp51_ = val;
#line 109 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp52_ = atoi (_tmp51_);
#line 109 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp53_ = ngettext ("File", "Files", (gulong) _tmp52_);
#line 109 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp54_ = g_strdup (_tmp53_);
#line 109 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 109 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp54_;
#line 110 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 868 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label5) ? _tmp33_label5 : (_tmp33_label5 = g_quark_from_static_string ("nfo:Folder")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 874 "tracker-stats.c"
							default:
							{
								const gchar* _tmp55_ = NULL;
								gint _tmp56_ = 0;
								const gchar* _tmp57_ = NULL;
								gchar* _tmp58_ = NULL;
#line 112 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp55_ = val;
#line 112 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp56_ = atoi (_tmp55_);
#line 112 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp57_ = ngettext ("Folder", "Folders", (gulong) _tmp56_);
#line 112 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp58_ = g_strdup (_tmp57_);
#line 112 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 112 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp58_;
#line 113 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 895 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label6) ? _tmp33_label6 : (_tmp33_label6 = g_quark_from_static_string ("nfo:Image")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 901 "tracker-stats.c"
							default:
							{
								const gchar* _tmp59_ = NULL;
								gint _tmp60_ = 0;
								const gchar* _tmp61_ = NULL;
								gchar* _tmp62_ = NULL;
#line 115 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp59_ = val;
#line 115 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp60_ = atoi (_tmp59_);
#line 115 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp61_ = ngettext ("Image", "Images", (gulong) _tmp60_);
#line 115 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp62_ = g_strdup (_tmp61_);
#line 115 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 115 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp62_;
#line 116 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 922 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label7) ? _tmp33_label7 : (_tmp33_label7 = g_quark_from_static_string ("nfo:SoftwareApplication")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 928 "tracker-stats.c"
							default:
							{
								const gchar* _tmp63_ = NULL;
								gint _tmp64_ = 0;
								const gchar* _tmp65_ = NULL;
								gchar* _tmp66_ = NULL;
#line 118 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp63_ = val;
#line 118 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp64_ = atoi (_tmp63_);
#line 118 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp65_ = ngettext ("Application", "Applications", (gulong) _tmp64_);
#line 118 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp66_ = g_strdup (_tmp65_);
#line 118 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 118 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp66_;
#line 119 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 949 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label8) ? _tmp33_label8 : (_tmp33_label8 = g_quark_from_static_string ("nfo:Video")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 955 "tracker-stats.c"
							default:
							{
								const gchar* _tmp67_ = NULL;
								gint _tmp68_ = 0;
								const gchar* _tmp69_ = NULL;
								gchar* _tmp70_ = NULL;
#line 122 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp67_ = val;
#line 122 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp68_ = atoi (_tmp67_);
#line 122 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp69_ = ngettext ("Video", "Videos", (gulong) _tmp68_);
#line 122 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp70_ = g_strdup (_tmp69_);
#line 122 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 122 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp70_;
#line 123 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 976 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label9) ? _tmp33_label9 : (_tmp33_label9 = g_quark_from_static_string ("nmm:MusicAlbum")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 982 "tracker-stats.c"
							default:
							{
								const gchar* _tmp71_ = NULL;
								gint _tmp72_ = 0;
								const gchar* _tmp73_ = NULL;
								gchar* _tmp74_ = NULL;
#line 125 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp71_ = val;
#line 125 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp72_ = atoi (_tmp71_);
#line 125 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp73_ = ngettext ("Album", "Albums", (gulong) _tmp72_);
#line 125 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp74_ = g_strdup (_tmp73_);
#line 125 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 125 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp74_;
#line 126 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 1003 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label10) ? _tmp33_label10 : (_tmp33_label10 = g_quark_from_static_string ("nmm:MusicPiece")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 1009 "tracker-stats.c"
							default:
							{
								const gchar* _tmp75_ = NULL;
								gint _tmp76_ = 0;
								const gchar* _tmp77_ = NULL;
								gchar* _tmp78_ = NULL;
#line 128 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp75_ = val;
#line 128 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp76_ = atoi (_tmp75_);
#line 128 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp77_ = ngettext ("Music Track", "Music Tracks", (gulong) _tmp76_);
#line 128 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp78_ = g_strdup (_tmp77_);
#line 128 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 128 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp78_;
#line 129 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 1030 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label11) ? _tmp33_label11 : (_tmp33_label11 = g_quark_from_static_string ("nmm:Photo")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 1036 "tracker-stats.c"
							default:
							{
								const gchar* _tmp79_ = NULL;
								gint _tmp80_ = 0;
								const gchar* _tmp81_ = NULL;
								gchar* _tmp82_ = NULL;
#line 131 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp79_ = val;
#line 131 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp80_ = atoi (_tmp79_);
#line 131 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp81_ = ngettext ("Photo", "Photos", (gulong) _tmp80_);
#line 131 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp82_ = g_strdup (_tmp81_);
#line 131 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 131 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp82_;
#line 132 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 1057 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label12) ? _tmp33_label12 : (_tmp33_label12 = g_quark_from_static_string ("nmm:Playlist")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 1063 "tracker-stats.c"
							default:
							{
								const gchar* _tmp83_ = NULL;
								gint _tmp84_ = 0;
								const gchar* _tmp85_ = NULL;
								gchar* _tmp86_ = NULL;
#line 134 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp83_ = val;
#line 134 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp84_ = atoi (_tmp83_);
#line 134 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp85_ = ngettext ("Playlist", "Playlists", (gulong) _tmp84_);
#line 134 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp86_ = g_strdup (_tmp85_);
#line 134 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 134 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp86_;
#line 135 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 1084 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label13) ? _tmp33_label13 : (_tmp33_label13 = g_quark_from_static_string ("nmo:Email")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 1090 "tracker-stats.c"
							default:
							{
								const gchar* _tmp87_ = NULL;
								gint _tmp88_ = 0;
								const gchar* _tmp89_ = NULL;
								gchar* _tmp90_ = NULL;
#line 137 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp87_ = val;
#line 137 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp88_ = atoi (_tmp87_);
#line 137 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp89_ = ngettext ("Email", "Emails", (gulong) _tmp88_);
#line 137 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp90_ = g_strdup (_tmp89_);
#line 137 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 137 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp90_;
#line 138 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 1111 "tracker-stats.c"
							}
						}
					} else if (_tmp34_ == ((0 != _tmp33_label14) ? _tmp33_label14 : (_tmp33_label14 = g_quark_from_static_string ("nfo:Bookmark")))) {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 1117 "tracker-stats.c"
							default:
							{
								const gchar* _tmp91_ = NULL;
								gint _tmp92_ = 0;
								const gchar* _tmp93_ = NULL;
								gchar* _tmp94_ = NULL;
#line 140 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp91_ = val;
#line 140 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp92_ = atoi (_tmp91_);
#line 140 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp93_ = ngettext ("Bookmark", "Bookmarks", (gulong) _tmp92_);
#line 140 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_tmp94_ = g_strdup (_tmp93_);
#line 140 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								_g_free0 (key_used);
#line 140 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								key_used = _tmp94_;
#line 141 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								break;
#line 1138 "tracker-stats.c"
							}
						}
					} else {
#line 95 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
						switch (0) {
#line 1144 "tracker-stats.c"
							default:
							{
#line 144 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
								continue;
#line 1149 "tracker-stats.c"
							}
						}
					}
#line 147 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp95_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 12);
#line 147 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					g_object_ref_sink (_tmp95_);
#line 147 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					box = _tmp95_;
#line 148 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp96_ = key_used;
#line 148 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp97_ = (GtkLabel*) gtk_label_new (_tmp96_);
#line 148 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					g_object_ref_sink (_tmp97_);
#line 148 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					label_key = _tmp97_;
#line 149 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp98_ = val;
#line 149 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp99_ = (GtkLabel*) gtk_label_new (_tmp98_);
#line 149 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					g_object_ref_sink (_tmp99_);
#line 149 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					label_val = _tmp99_;
#line 158 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp100_ = label_key;
#line 158 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					gtk_misc_set_alignment ((GtkMisc*) _tmp100_, 0.0f, 0.5f);
#line 159 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp101_ = label_val;
#line 159 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					gtk_misc_set_alignment ((GtkMisc*) _tmp101_, 0.0f, 0.5f);
#line 161 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp102_ = box;
#line 161 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp103_ = label_key;
#line 161 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					gtk_box_pack_start (_tmp102_, (GtkWidget*) _tmp103_, TRUE, TRUE, (guint) 0);
#line 162 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp104_ = box;
#line 162 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp105_ = label_val;
#line 162 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					gtk_box_pack_start (_tmp104_, (GtkWidget*) _tmp105_, FALSE, TRUE, (guint) 0);
#line 164 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp106_ = sizegroup;
#line 164 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp107_ = label_key;
#line 164 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					gtk_size_group_add_widget (_tmp106_, (GtkWidget*) _tmp107_);
#line 166 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp108_ = vbox;
#line 166 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_tmp109_ = box;
#line 166 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					gtk_box_pack_start (_tmp108_, (GtkWidget*) _tmp109_, TRUE, TRUE, (guint) 0);
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_g_object_unref0 (label_val);
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_g_object_unref0 (label_key);
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_g_object_unref0 (box);
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_g_free0 (key_used);
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_g_free0 (val);
#line 88 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
					_g_free0 (key);
#line 1219 "tracker-stats.c"
				}
			}
		}
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_result_ = (_vala_array_free (_result_, _result__length1 * _result__length2, (GDestroyNotify) g_free), NULL);
#line 1225 "tracker-stats.c"
	}
	goto __finally12;
	__catch12_g_dbus_error:
	{
		GError* e = NULL;
		GError* _tmp110_ = NULL;
		const gchar* _tmp111_ = NULL;
		gchar* _tmp112_ = NULL;
		gchar* _tmp113_ = NULL;
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		e = _inner_error_;
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_inner_error_ = NULL;
#line 169 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp110_ = e;
#line 169 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp111_ = _tmp110_->message;
#line 169 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp112_ = g_strconcat ("Could not get Tracker statistics: ", _tmp111_, NULL);
#line 169 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_tmp113_ = _tmp112_;
#line 169 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		g_warning ("tracker-stats.vala:169: %s", _tmp113_);
#line 169 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_free0 (_tmp113_);
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_error_free0 (e);
#line 1253 "tracker-stats.c"
	}
	__finally12:
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_object_unref0 (sizegroup);
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_object_unref0 (label);
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		_g_object_unref0 (vbox);
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		g_clear_error (&_inner_error_);
#line 85 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		return;
#line 1270 "tracker-stats.c"
	}
#line 173 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp114_ = vbox;
#line 173 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_box_set_spacing (_tmp114_, 10);
#line 176 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_dialog_add_button ((GtkDialog*) self, "_Close", (gint) GTK_RESPONSE_CLOSE);
#line 179 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_signal_connect_object ((GtkDialog*) self, "response", (GCallback) _tracker_stats_on_response_gtk_dialog_response, self, 0);
#line 181 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	gtk_widget_show_all ((GtkWidget*) self);
#line 62 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_g_object_unref0 (sizegroup);
#line 62 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_g_object_unref0 (label);
#line 62 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_g_object_unref0 (vbox);
#line 1288 "tracker-stats.c"
}


static void tracker_stats_on_response (TrackerStats* self, GtkDialog* source, gint response_id) {
	gint _tmp0_ = 0;
#line 184 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_return_if_fail (self != NULL);
#line 184 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_return_if_fail (source != NULL);
#line 185 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_tmp0_ = response_id;
#line 185 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	switch (_tmp0_) {
#line 185 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		case GTK_RESPONSE_CLOSE:
#line 1304 "tracker-stats.c"
		{
#line 187 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			gtk_widget_destroy ((GtkWidget*) self);
#line 188 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
			break;
#line 1310 "tracker-stats.c"
		}
		default:
#line 185 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
		break;
#line 1315 "tracker-stats.c"
	}
}


static void tracker_stats_class_init (TrackerStatsClass * klass) {
#line 30 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	tracker_stats_parent_class = g_type_class_peek_parent (klass);
#line 30 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	g_type_class_add_private (klass, sizeof (TrackerStatsPrivate));
#line 30 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	G_OBJECT_CLASS (klass)->finalize = tracker_stats_finalize;
#line 1327 "tracker-stats.c"
}


static void tracker_stats_instance_init (TrackerStats * self) {
#line 30 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	self->priv = TRACKER_STATS_GET_PRIVATE (self);
#line 1334 "tracker-stats.c"
}


static void tracker_stats_finalize (GObject* obj) {
	TrackerStats * self;
#line 30 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TRACKER_TYPE_STATS, TrackerStats);
#line 31 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	_g_object_unref0 (self->priv->tracker);
#line 30 "/home/carlos/Source/gnome/tracker/src/tracker-needle/tracker-stats.vala"
	G_OBJECT_CLASS (tracker_stats_parent_class)->finalize (obj);
#line 1346 "tracker-stats.c"
}


GType tracker_stats_get_type (void) {
	static volatile gsize tracker_stats_type_id__volatile = 0;
	if (g_once_init_enter (&tracker_stats_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (TrackerStatsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) tracker_stats_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (TrackerStats), 0, (GInstanceInitFunc) tracker_stats_instance_init, NULL };
		GType tracker_stats_type_id;
		tracker_stats_type_id = g_type_register_static (gtk_dialog_get_type (), "TrackerStats", &g_define_type_info, 0);
		g_once_init_leave (&tracker_stats_type_id__volatile, tracker_stats_type_id);
	}
	return tracker_stats_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



