usr/lib/tracker/tracker-miner-fs
usr/lib/tracker/tracker-miner-user-guides
usr/lib/tracker/tracker-miner-apps
etc/xdg/autostart/tracker-miner-fs.desktop
etc/xdg/autostart/tracker-miner-user-guides.desktop
etc/xdg/autostart/tracker-miner-apps.desktop
usr/lib/systemd/user/tracker-miner-apps.service
usr/lib/systemd/user/tracker-miner-fs.service
usr/lib/systemd/user/tracker-miner-user-guides.service
usr/share/dbus-1/services/org.freedesktop.Tracker1.Miner.Applications.service
usr/share/dbus-1/services/org.freedesktop.Tracker1.Miner.Files.service
usr/share/dbus-1/services/org.freedesktop.Tracker1.Miner.Userguides.service
usr/share/man/man1/tracker-miner-fs.1
usr/share/tracker/miners/org.freedesktop.Tracker1.Miner.Applications.service
usr/share/tracker/miners/org.freedesktop.Tracker1.Miner.Files.service
usr/share/tracker/miners/org.freedesktop.Tracker1.Miner.Userguides.service
usr/share/tracker/tracker-miner-files-index.xml
debian/30-tracker.conf etc/sysctl.d/
