usr/bin/tracker-control
usr/share/man/man1/tracker-control.1
usr/share/dbus-1/services/org.freedesktop.Tracker1.service

usr/share/tracker/tracker-miner.xml
usr/share/tracker/tracker-miner-web.xml
usr/share/tracker/tracker-statistics.xml
usr/share/tracker/tracker-backup.xml
usr/share/tracker/tracker-resources.xml
usr/share/tracker/tracker-status.xml

usr/lib/tracker/tracker-store

usr/share/man/man1/tracker-store.1
usr/share/man/man5/tracker-store.cfg.5
usr/share/man/man5/tracker-fts.cfg.5

usr/share/locale/
usr/share/tracker/ontologies/
usr/share/tracker/languages/

etc/xdg/autostart/tracker-store.desktop

usr/lib/tracker-0.10/libtracker-data.so.*
usr/lib/tracker-0.10/sparql-modules/*.so
