debian/tmp/usr/lib/tracker/trackerd
debian/tmp/usr/lib/tracker/tracker-extract
debian/tmp/usr/lib/tracker/tracker-indexer
debian/tmp/usr/lib/tracker/*.so*
debian/tmp/usr/share/dbus-1/services/
debian/tmp/usr/share/tracker/*.xml
debian/tmp/usr/share/tracker/*.sql
debian/tmp/usr/share/tracker/languages/
debian/tmp/usr/share/tracker/services/
debian/tmp/usr/share/tracker/modules/
debian/tmp/usr/share/locale/
debian/tmp/usr/share/icons/
debian/tmp/usr/lib/tracker/filters/
debian/tmp/usr/lib/tracker/extract-modules/*.so
debian/tmp/usr/lib/tracker/indexer-modules/*.so
debian/tmp/usr/lib/tracker/push-modules/daemon/*.so
debian/tmp/usr/lib/tracker/push-modules/indexer/*.so
debian/tmp/etc/xdg/autostart/trackerd.desktop
debian/tmp/etc/xdg/autostart/trackerd.desktop usr/share/autostart/
debian/30-tracker.conf etc/sysctl.d
